### ISSUE TITLE
Underflow error

### ISSUE THREAD

**Issue by mlbendall** [nixonlab/stellarscope#18]
Underflow error. This is happening when using alignments with high values for `--outFilterMultimapScoreRange` (15 in this case). Probably what is happening is that including more suboptimal alignments results in very very small numbers (probabilities?) and causes underflow. Fix by switching to longdouble in these operations.

```
Traceback (most recent call last):
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/bin/stellarscope", line 8, in <module>
    sys.exit(stellarscope())
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/lib/python3.10/site-packages/stellarscope/__main__.py", line 141, in stellarscope
    args.func(args)
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/lib/python3.10/site-packages/stellarscope/stellarscope_assign.py", line 332, in run
    st_model = model.fit_pooling_model(st_obj, opts)
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/lib/python3.10/site-packages/stellarscope/utils/model.py", line 1146, in fit_pooling_model
    st_model = fit_pseudobulk(_scoremat)
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/lib/python3.10/site-packages/stellarscope/utils/model.py", line 1048, in fit_pseudobulk
    st_model.em(use_likelihood=opts.use_likelihood)
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/lib/python3.10/site-packages/stellarscope/utils/model.py", line 773, in em
    _z = self.estep(self.pi, self.theta)
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/lib/python3.10/site-packages/stellarscope/utils/model.py", line 712, in estep
    return _n.norm(1)
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/lib/python3.10/site-packages/stellarscope/utils/sparse_plus.py", line 51, in norm
    return self._norm(axis)
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/lib/python3.10/site-packages/stellarscope/utils/sparse_plus.py", line 59, in _norm
    return self.multiply(_recip0(self.sum(1)))
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/lib/python3.10/site-packages/stellarscope/utils/sparse_plus.py", line 203, in multiply
    return type(self)(super().multiply(other))
  File "/fsx/projects/alignment-tests-for-stellarscope/.snakemake/conda/87c2c9149ad9b04b9e2b40474ecea3d1/lib/python3.10/site-packages/scipy/sparse/_compressed.py", line 470, in multiply
    data = np.multiply(ret.data, other[ret.row].ravel())
FloatingPointError: underflow encountered in multiply
```

**Comment by mlbendall** [comment]
Resolved by 17c8933 and 148e9b2
