### ISSUE TITLE
Error-Traceback (most recent call last): 

### ISSUE THREAD

**Issue by roofya** [nixonlab/stellarscope#23]
Dear nixonlab,

I gor error related to some package 🙁 

stellarscope cellsort \
  --nproc 12 \
  --tempdir /tmp \
  --outfile results/stellarscope/Aligned.sortedByCB.bam \
  results/star_alignment/Aligned.sortedByCoord.out.bam \
  results/star_alignment/Solo.out/Gene/filtered/barcodes.tsv

Traceback (most recent call last):
  File "/programs/miniconda3/envs/stellarscope_protocol_env/bin/stellarscope", line 33, in <module>
    sys.exit(load_entry_point('stellarscope', 'console_scripts', 'stellarscope')())
  File "/programs/miniconda3/envs/stellarscope_protocol_env/bin/stellarscope", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/programs/miniconda3/envs/stellarscope_protocol_env/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/programs/miniconda3/envs/stellarscope_protocol_env/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for stellarscope

**Comment by mlbendall** [comment]
I will need more details about how you installed stellarscope.
