### ISSUE TITLE
OverflowError: Python integer out of bounds for uint32

### ISSUE THREAD

**Issue by olivertam** [nixonlab/stellarscope#25]
Hi,

I've encountered the following issue when running `stellascope assign`:

```
 #-------------Stage 0: Initialize Stellarscope-----
--------# (from startrun in stages.py:34)
Traceback (most recent call last):
  File "/gpfs/bin/stellarscope", line 33, in <module>
    sys.exit(load_entry_point('stellarscope==1.4', 'console_scripts', 'stellarscope')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/lib/python3.12/site-packages/stellarscope-1.4-py3.12-linux-x86_64.egg/stellarscope/__main__.py", line 142, in stellarscope
    args.func(args)
  File "/gpfs/lib/python3.12/site-packages/stellarscope-1.4-py3.12-linux-x86_64.egg/stellarscope/stellarscope_assign.py", line 126, in run
    st_obj = InitStellarscope(curstage).run(opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/lib/python3.12/site-packages/stellarscope-1.4-py3.12-linux-x86_64.egg/stellarscope/stages.py", line 52, in run
    opts.init_rng()
  File "/gpfs/lib/python3.12/site-packages/stellarscope-1.4-py3.12-linux-x86_64.egg/stellarscope/stellarscope_assign.py", line 94, in init_rng
    self.seed = np.uint32(_tmpseed) if _tmpseed != 1 else None
                ^^^^^^^^^^^^^^^^^^^
OverflowError: Python integer 4558202177660785 out of bounds for uint32
```

Here is the command line I used:
```
$ stellarscope assign --exp_tag ${BASE}_individual --outdir $PWD --nproc 10 --stranded_mode F --whitelist ${BC} --pooling_mode individual --reassign_mode best_exclude --max_iter 500 --updated_sam ${BASE}.sortedByCB.bam hg38_stellarscope_retroV1.gtf
```

Here are my conda environment with respect to your `environment.yaml` file:
```
# Name                    Version                   Build  Channel
cython                    3.0.10          py312h30efb56_0    conda-forge
future                    1.0.0              pyhd8ed1ab_0    conda-forge
htslib                    1.20                 h81da01d_0    bioconda
intervaltree              3.1.0              pyhd8ed1ab_1    conda-forge
numpy                     2.0.0rc1                 pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pip                       24.0               pyhd8ed1ab_0    conda-forge
pysam                     0.22.1                   pypi_0    pypi
python                    3.12.3          hab00c5b_0_cpython    conda-forge
pyyaml                    6.0.1           py312h98912ed_1    conda-forge
samtools                  1.20                 h50ea8bc_0    bioconda
scipy                     1.13.0                   pypi_0    pypi
stellarscope              1.4                      pypi_0    pypi
```

Any help would be much appreciated.

Thanks.

**Comment by mlbendall** [comment]
Resolved this with 4ad3e7e
